# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobufs/agent.proto\"x\n\x0b\x61gent_query\x12\x11\n\tagentType\x18\x01 \x01(\t\x12\x11\n\tagentName\x18\x02 \x01(\t\x12\x10\n\x08roomName\x18\x03 \x01(\t\x12\x0f\n\x07\x61piJson\x18\x04 \x01(\t\x12\r\n\x05\x63olor\x18\x07 \x01(\t\x12\x11\n\tpromptDir\x18\x08 \x01(\t\"\x1e\n\x0b\x61gent_state\x12\x0f\n\x07\x61gentID\x18\x01 \x01(\x05\"m\n\nagent_info\x12-\n\tagentInfo\x18\x02 \x03(\x0b\x32\x1a.agent_info.AgentInfoEntry\x1a\x30\n\x0e\x41gentInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x65mpty2\x8c\x01\n\x05\x61gent\x12,\n\x0c\x63reate_agent\x12\x0c.agent_query\x1a\x0c.agent_state\"\x00\x12&\n\x0c\x64\x65lete_agent\x12\x0c.agent_state\x1a\x06.empty\"\x00\x12-\n\x0eget_agent_info\x12\x0c.agent_state\x1a\x0b.agent_info\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGENT_INFO_AGENTINFOENTRY._options = None
  _AGENT_INFO_AGENTINFOENTRY._serialized_options = b'8\001'
  _globals['_AGENT_QUERY']._serialized_start=25
  _globals['_AGENT_QUERY']._serialized_end=145
  _globals['_AGENT_STATE']._serialized_start=147
  _globals['_AGENT_STATE']._serialized_end=177
  _globals['_AGENT_INFO']._serialized_start=179
  _globals['_AGENT_INFO']._serialized_end=288
  _globals['_AGENT_INFO_AGENTINFOENTRY']._serialized_start=240
  _globals['_AGENT_INFO_AGENTINFOENTRY']._serialized_end=288
  _globals['_EMPTY']._serialized_start=290
  _globals['_EMPTY']._serialized_end=297
  _globals['_AGENT']._serialized_start=300
  _globals['_AGENT']._serialized_end=440
# @@protoc_insertion_point(module_scope)
